# Generated by Django 3.0.5 on 2020-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tembici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='classificacao',
            field=models.SmallIntegerField(choices=[(1, 'Trabalho'), (2, 'Atividade física'), (3, 'Lazer'), (4, 'Deslocamento')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nota',
            field=models.SmallIntegerField(default=1),
        ),
    ]
