# Generated by Django 3.0.5 on 2020-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tembici', '0002_auto_20200430_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='data_fim',
            field=models.DateTimeField(),
        ),
    ]
