# Generated by Django 3.0.5 on 2020-04-30 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tembici', '0003_auto_20200430_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 1, 45, 12, 575504)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 1, 45, 12, 575504)),
        ),
    ]
