# Generated by Django 3.0.5 on 2020-04-30 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tembici', '0004_auto_20200430_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 15, 5, 46, 197166)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 15, 5, 46, 197166)),
        ),
    ]
